### ISSUE TITLE
Weather API not working

### ISSUE THREAD

**Issue by AshwiniR1802** [SE-H-W/Project-02#2]
The information is not fetched properly because it is deprecated.

**Comment by Nirmit73** [comment]
What should be our approach?

**Comment by AshwiniR1802** [comment]
We should change the host URL to something other than Rapid API.

**Comment by kahaanpatel5** [comment]
Approach Steps:
1. We should update the .env file for new host url as old one is deprecated.
2. Base url in the weather_bit_config should also be changed in settings.py
3. We also need to change info/helpers/weather.py in order to initialize URL with required parameters: protocol, host, and port.
4. Also the url path needs to be changed in info/utils/weather.py

**Comment by kahaanpatel5** [comment]
![image](https://github.com/user-attachments/assets/ad18c139-bff1-4f3a-99da-cbdbdd9f4c0f)
![image](https://github.com/user-attachments/assets/9e6c1fd2-c29a-490d-92e9-133eaf6b2c09)

Issue resolved and weather API is working

**Comment by AshwiniR1802** [comment]
ok done
